apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  ingress:
    enabled: true
    hosts:
      - example.com
    ingressClassName: nginx
  storage:
    type: memory
  strategy: allinone
