apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/part-of: bets-system
  name: matches
  namespace: continuous-delivery
spec:
  destination:
    namespace: bets-system
    server: https://kubernetes.default.svc
  project: application
  source:
    helm:
      valueFiles:
        - values-linkerd.yaml
    path: stable/matches
    repoURL: https://github.com/claudioed/bets-helm.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
