apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: demo
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          nodeSelector:
            ingress-ready: "true"
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
                nodePort: 30002
              - name: http2
                port: 80
                targetPort: 8080
                nodePort: 30000
              - name: https
                port: 443
                targetPort: 8443
                nodePort: 30001
  values:
    gateways:
      istio-ingressgateway:
        type: NodePort
    global:
      defaultPodDisruptionBudget:
        enabled: false
      logging:
        level: default:debug
      proxy:
        logLevel: debug
        componentLogLevel: misc:debug
