apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops
  namespace: "${namespace}"
spec:
  ignore: |
    # exclude all
    /*
    # include charts dir
    !/charts
  interval: 60s
  ref:
    semver: "${semver}"
  timeout: 60s
  url: https://github.com/weaveworks/weave-gitops
